apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier-deploy
  labels:
    app: two-tier-app


spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-tier-app

  template:
    metadata:
      labels:
        app: two-tier-app

    spec:
      containers:
        - name: two-tier-app-cont
          image: ankitrawat3987/flaskapp:latest
          #image: trainwithshubham/flaskapp:latest
          env:
            - name: MYSQL_HOST
              value: "10.110.223.181"
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_DB
              value: "mydb"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
